name: "Setup clasp auth"
description: "Generate .clasprc.json from GitHub Secrets"
author: "ciderjs/luth"
branding:
  icon: "lock"
  color: "red"
inputs:
  json:
    description: "Uploaded .clasprc.json as Base64-encoded string"
    required: true
    default: "{}"
runs:
  using: "composite"
  steps:
    - name: Restore .clasprc.json
      shell: bash
      run: |
        echo "$CLASPRC_JSON" > base64 -d > ~/.clasprc.json
      env:
        CLASPRC_JSON: ${{ inputs.json }}
